name: sam_3d_body
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.12.2=hca03da5_0
  - expat=2.7.4=h50f4ffc_0
  - libcxx=21.1.8=hb4ce287_0
  - libexpat=2.7.4=h50f4ffc_0
  - libffi=3.4.4=hca03da5_1
  - libzlib=1.3.1=h5f15de7_0
  - ncurses=6.5=hee39554_0
  - openssl=3.0.19=ha0b305a_0
  - packaging=25.0=py311hca03da5_1
  - pip=25.3=pyhc872135_0
  - python=3.11.14=hf701271_0
  - readline=8.3=h0b18652_0
  - setuptools=80.10.2=py311hca03da5_0
  - sqlite=3.51.1=hab6afd1_0
  - tk=8.6.15=hcd8a7d5_0
  - tzdata=2025c=he532380_0
  - wheel=0.46.3=py311hca03da5_0
  - xz=5.6.4=h80987f9_1
  - zlib=1.3.1=h5f15de7_0
  - pip:
      - absl-py==2.4.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - appdirs==1.4.4
      - appnope==0.1.4
      - attrs==25.4.0
      - black==26.1.0
      - braceexpand==0.1.7
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - chump==1.6.0
      - click==8.3.1
      - clip==1.0
      - cloudpickle==3.1.2
      - colorlog==6.10.1
      - contourpy==1.3.3
      - cycler==0.12.1
      - cython==3.2.4
      - detectron2==0.6
      - dill==0.4.1
      - einops==0.8.2
      - ffmpeg==1.4
      - filelock==3.20.3
      - fonttools==4.61.1
      - freetype-py==2.5.1
      - frozenlist==1.8.0
      - fsspec==2026.2.0
      - ftfy==6.3.1
      - fvcore==0.1.5.post20221221
      - gitdb==4.0.12
      - gitpython==3.1.46
      - grpcio==1.78.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - hydra-submitit-launcher==1.2.0
      - idna==3.11
      - imageio==2.37.2
      - iniconfig==2.3.0
      - iopath==0.1.10
      - jinja2==3.1.6
      - joblib==1.5.3
      - jsonlines==4.0.0
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - lightning-utilities==0.15.2
      - loguru==0.7.3
      - markdown==3.10.1
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mdurl==0.1.2
      - mpmath==1.3.0
      - multidict==6.7.1
      - mypy-extensions==1.1.0
      - networkx==3.2.1
      - numpy==2.4.2
      - omegaconf==2.3.0
      - opencv-python==4.13.0.92
      - optree==0.18.0
      - pandas==3.0.0
      - pathspec==1.0.4
      - pillow==12.1.0
      - platformdirs==4.5.1
      - pluggy==1.6.0
      - portalocker==3.2.0
      - propcache==0.4.1
      - protobuf==6.33.5
      - pycocotools==2.0.11
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pyglet==2.1.13
      - pygments==2.19.2
      - pyopengl==3.1.0
      - pyparsing==3.3.2
      - pyrender==0.1.45
      - pyrootutils==1.0.4
      - pytest==9.0.2
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.2.1
      - pytokens==0.4.1
      - pytorch-lightning==2.6.1
      - pyyaml==6.0.3
      - regex==2026.1.15
      - requests==2.32.5
      - rich==14.3.2
      - roma==1.5.5
      - safetensors==0.7.0
      - scikit-image==0.26.0
      - scipy==1.17.0
      - seaborn==0.13.2
      - sentry-sdk==2.52.0
      - shellingham==1.5.4
      - six==1.17.0
      - smmap==5.0.2
      - submitit==1.5.4
      - sympy==1.14.0
      - tabulate==0.9.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - termcolor==3.3.0
      - tifffile==2026.1.28
      - timm==1.0.24
      - torch==2.10.0
      - torchmetrics==1.8.2
      - torchvision==0.25.0
      - tqdm==4.67.3
      - trimesh==4.11.1
      - typer-slim==0.21.1
      - typing-extensions==4.15.0
      - typing-inspection==0.4.2
      - urllib3==2.6.3
      - wandb==0.24.2
      - wcwidth==0.6.0
      - webdataset==1.0.2
      - werkzeug==3.1.5
      - xtcocotools==1.14.3
      - yacs==0.1.8
      - yarl==1.22.0
prefix: /opt/homebrew/anaconda3/envs/sam_3d_body
